services:
  mongodb:
    image: mongo:latest
    container_name: week12-mongo
    restart: always
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=password
      - MONGO_INITDB_DATABASE=week12
    ports:
      - "27017:27017"
    volumes:
      - ./docker/mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro
      - mongo-data:/data/db

volumes:
  mongo-data: